name: MoneySystem
version: '1.0-SNAPSHOT'
main: de.jonasheilig.moneySystem.MoneySystem
api-version: '1.21'
commands:
  money:
    description: Zeigt dein Geld an.
  setmoney:
    description: Setzt das Geld eines Spielers.
    usage: /setmoney <Spieler> <Betrag>
    permission: moneysystem.setmoney
  moneytool:
    description: Verwaltung von Spielergeld.
    usage: /moneytool <get|add|remove> <Spieler> <Betrag>
    permission: moneysystem.moneytool
  adminshop:
    description: Öffnet den AdminShop.
    usage: /adminshop
  editadminshop:
    description: Öffnet den EditAdminShop.
    usage: /editadminshop
    permission: moneysystem.editadminshop
permissions:
  moneysystem.setmoney:
    description: Erlaubt das Setzen des Geldes eines Spielers.
    default: op
  moneysystem.moneytool:
    description: Erlaubt die Verwaltung des Geldes von Spielern.
    default: op
  moneysystem.editadminshop:
    description: Erlaubt den Zugriff auf den EditAdminShop.
    default: op