name: MoneySystem
version: '1.0-SNAPSHOT'
main: de.jonasheilig.moneySystem.MoneySystem
api-version: '1.21'
commands:
  money:
    description: Zeigt dein Geld an.
  setmoney:
    description: Setzt das Geld eines Spielers.
    usage: /setmoney <Spieler> <Betrag>
    permission: moneysystem.setmoney
permissions:
  moneysystem.setmoney:
    description: Erlaubt das Setzen des Geldes eines Spielers.
    default: op